Prevent ANR duplicates
backtrace-labs/backtrace-android pull request #39
Opened 2021-11-22 20:07 UTC by konraddysput

# Why

In the past when ANR took longer than expected, backtrace-android might report multiple ANRs when the library shouldn't. This diff prevents duplicates.

2021-11-22 20:11 UTC, vlussenburg requested changes

2021-11-22 20:11 UTC, vlussenburg commented on backtrace-library/src/main/java/backtraceio/library/watchdog/BacktraceANRWatchdog.java
> +                // skiping, because we already reported an ANR report for current ANR
skipPing

2021-11-22 20:51 UTC, rqbacktrace approved these changes
Looks good to me! While we are in ANR state, we will only send one report. We won't send another report until we have newly entered ANR state again.

2021-11-23 19:41 UTC, vlussenburg approved these changes

2021-11-23 20:17 UTC, merged