Handle corrupt or empty database records
backtrace-labs/backtrace-android pull request #74
Opened 2022-10-17 23:53 UTC by selalipop

In cases where a crash record file is corrupted or empty, `BacktraceDatabaseRecord.readFromFile` may return null, causing a crash when the result accessed

This PR adds handling for this case by treating null return values as an invalid record

2022-10-18 12:30 UTC, konraddysput approved these changes

2022-10-20 05:43 UTC, selalipop commented
Yes it will! Thank you for the catch 😁 

And I'll come up with some test cases for this

2022-11-28 17:43 UTC, BartoszLitwiniuk requested changes
Please check my comments

2022-11-28 17:43 UTC, BartoszLitwiniuk commented on backtrace-library/src/main/java/backtraceio/library/BacktraceDatabase.java
> +            if (record == null || !record.valid()) {
Your solution will cause NullPointerException if record will be null

2022-11-28 17:44 UTC, BartoszLitwiniuk commented
I'm closing this PR and I will open new one with proper fix and unit test

2022-11-28 17:44 UTC, closed without merging